### PR TITLE
Update versions

### PR DESCRIPTION
**Pull request by tskisner**
- Update package versions for so3g, toast, and pixell
- Patch compilation of `libactpol_deps` and `pixell` with conda compilers.  Will upstream those patches soon.
- Switch to python-3.11 for most configs
- Get pysm3 from conda-forge instead of pypi
- Remove debug compile flags

### CODE REVIEW

**Comment by iparask** [comment]
@tskisner, I got a warning message that `conda-verify` was failing from `conda build`. I had to install it manually so that builds could be verified. You may want to install it regardless of the type of conda env (mamba or not). Despite the warning, the environment is installed correctly.

**Comment by tskisner** [comment]
Hi @iparask , for non-micromamba environments, the conda tools (build, verify, index) are installed in the base environment.  This is done by the "bootstrap" [helper script](https://github.com/simonsobs/soconda/blob/bbc66c2aea726a17b77ba1b445dfda469f92374f/tools/bootstrap_base.sh#L36).  If you created your base environment manually or through some other way, then you can install those packages into base with the same commands:
```
conda update -n base --yes --all conda
conda install -n base --yes --all conda-libmamba-solver conda-build conda-verify conda-index
```

**Comment by tskisner** [comment]
Hi @iparask , I think all of the issues have been fixed here.  Could you take a quick look and see if there are any issues you see?  [The tests seem to be passing](https://github.com/simonsobs/soconda/actions/runs/10688104008).

**Review by iparask — APPROVED** [review]
It looks good and it installed on Della.

**Pull request merged**
