### PR TITLE
Configuration changes

### PR DESCRIPTION
**Pull request by tskisner**
Reorganization of package lists into per-system directories.  Note this will be rebased after #7 is merged.  This also has a cleanup for the automated install on perlmutter.

### CODE REVIEW

**Comment by tskisner** [comment]
Hello @Bai-Chiang , would you be willing to review this PR?  The main change is adding per-machine config files, so that the default config for each system can be customized.

**Comment by Bai-Chiang** [comment]
It look good to me. I like the pre-machine config directory.

I think we could also put post-installation configuration steps into the pre-machine config directory. For example, [line 293](https://github.com/simonsobs/soconda/blob/117b3024d1dee9eabb621bbea1c674793ff14170/soconda.sh#L293) afterward, probably only applies to Perlmutter, different clusters will have different modules or jupyter notebook setup.

**Comment by tskisner** [comment]
I like the idea of making the creation of jupyter kernels and module files optional.  That is convenient for NERSC, site computing, and other shared centers, but less useful for someone's laptop.  I'll make that change later today.

**Comment by tskisner** [comment]
Ok, this is now implemented.  Each machine config has a `post_install.sh` file that is sourced.  At minimum this just has 2 switches for whether to install modulefiles and the jupyter kernel setup script.  Just to be clear, the module files and jupyter setup are generic and should work on any system (not just NERSC).  Note that I did lift the pinning of `pyfftw`, since it looks like [that upstream fix](https://github.com/conda-forge/pyfftw-feedstock/pull/60) should land soon.  If we see any problems in practice we could revert that, but it does limit us to python-3.10 to be compatible with that older version of pyfftw.

**Pull request merged**
